version: '3.5'
services:
 zabbix-server:
  image: zabbix/zabbix-server-mysql:centos-4.0-latest
  ports:
   - "10051:10051"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro 
   - zabbix-data:/usr/lib/zabbix/alertscripts
   - zabbix-data:/usr/lib/zabbix/externalscripts
   - zabbix-data:/var/lib/zabbix/export:rw
   - zabbix-data:/var/lib/zabbix/modules
   - zabbix-data:/var/lib/zabbix/enc
   - zabbix-data:/var/lib/zabbix/ssh_keys
   - zabbix-data:/var/lib/zabbix/mibs
  ulimits:
   nproc: 65535
   nofile:
    soft: 20000
    hard: 40000
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 1G
    reservations:
      cpus: '0.5'
      memory: 512M
  environment:
   - DB_SERVER_HOST=mysql-server
   - DB_SERVER_PORT=3306
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix
   - MYSQL_ROOT_PASSWORD=root_pwd
   - MYSQL_DATABASE=zabbix
   - ZBX_TIMEOUT=10
  depends_on:
   - mysql-server
  networks:
   zbx_net_backend:
     aliases:
      - zabbix-server
      - zabbix-server-mysql
      - zabbix-server-centos-mysql
      - zabbix-server-mysql-centos
   zbx_net_frontend:
  stop_grace_period: 30s
  sysctls:
   - net.ipv4.ip_local_port_range=1024 65000
   - net.ipv4.conf.all.accept_redirects=0
   - net.ipv4.conf.all.secure_redirects=0
   - net.ipv4.conf.all.send_redirects=0
  labels:
   com.zabbix.description: "Zabbix server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-server"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "centos"

 zabbix-web-nginx-mysql:
  image: zabbix/zabbix-web-nginx-mysql:centos-4.0-latest
  ports:
   - "80:8080"
   - "443:8443"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - zabbix-data:/etc/ssl/nginx
  deploy:
   resources:
    limits:
      cpus: '0.70'
      memory: 512M
    reservations:
      cpus: '0.5'
      memory: 256M
  environment:
   - ZBX_SERVER_HOST=zabbix-server
   - ZBX_SERVER_PORT=10051
   - DB_SERVER_HOST=mysql-server
   - DB_SERVER_PORT=3306
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix
   - MYSQL_ROOT_PASSWORD=root_pwd
   - MYSQL_DATABASE=zabbix
   - ZBX_SERVER_NAME=CSAZPP-ZABBIX
   - PHP_TZ=Asia/Hong_Kong
  depends_on:
   - mysql-server
   - zabbix-server
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost:8080/"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-nginx-mysql
     - zabbix-web-nginx-centos-mysql
     - zabbix-web-nginx-mysql-centos
   zbx_net_frontend:
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "centos"

 mysql-server:
  image: mysql:8.0
  command:
   - mysqld
   - --character-set-server=utf8
   - --collation-server=utf8_bin
   - --default-authentication-plugin=mysql_native_password
  volumes:
   - zabbix-data:/var/lib/mysql
  environment:
   - MYSQL_USER=zabbix
   - MYSQL_PASSWORD=zabbix
   - MYSQL_ROOT_PASSWORD=root_pwd
   - MYSQL_DATABASE=zabbix
  stop_grace_period: 1m
  networks:
   zbx_net_backend:
    aliases:
     - mysql-server
     - zabbix-database
     - mysql-database

networks:
  zbx_net_frontend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
  zbx_net_backend:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.239.0/24

volumes:
  zabbix-data:

